package com.example.aiza.core.model

import com.example.aiza.intent.AizaIntent
import com.example.aiza.tools.ToolResult
import java.util.UUID

/**
 * Encapsulates the final structured response generated by Aiza.
 */
data class AizaResponse(
    val id: String = UUID.randomUUID().toString(),
    val requestId: String,
    val text: String,
    val language: Language,
    val intent: AizaIntent,
    val toolResult: ToolResult? = null,
    val requiresConfirmation: Boolean = false,
    val pendingActionId: String? = null,
    val pendingActionDescription: String? = null,
    val executionDurationMs: Long = 0L,
    val timestamp: Long = System.currentTimeMillis()
)
